#端口号
server:
  port: 7000

# 扫描classpath下所有mybatis配置文件
mybatis:
  mapper-locations: classpath*:mappers/*.xml

# 日志配置
logging:
  config: classpath:logging-config.xml

# 内置初始化用户
init-user:
  userName: "google auth"
  password: "123456"

spring:
  profiles:
    active: local
  application:
    name: google-authenticator-service
  datasource:
    url: jdbc:mysql://localhost:3306/google_authenticator_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&useCompression=true&allowPublicKeyRetrieval=true
    username: root
    password: 'wj210523'
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 开启liquibase
  liquibase:
    enabled: true