#端口号
server:
  port: 1002

# 扫描classpath下所有mybatis配置文件
mybatis:
  mapper-locations: classpath*:mappers/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-dk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&useCompression=true&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver