#端口号
server:
  port: 7788

# 扫描classpath下所有mybatis配置文件
#mybatis:
#  mapper-locations: classpath*:mappers/*.xml

spring:
  profiles:
    active: local
  application:
    name: http-client-service
  # 文件大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  # Redis配置
  redis:
    cluster:
      nodes:
        - localhost:6379
      max-redirects: 5
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    password: 'xxxxx'
    database: 3
    timeout: 300