server:
  port: 8080

spring:
  application:
    name: springboot-quartz-3
  #引入数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test-quartz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&useCompression=true&allowPublicKeyRetrieval=true
    username: root
    password: wj210523
    driver-class-name: com.mysql.cj.jdbc.Driver