server:
  port: 8080

spring:
  application:
    name: springboot-quartz-001
  #引入数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: wj210523
    driver-class-name: com.mysql.cj.jdbc.Driver